completed css-three-column-layout-exercise - Nick Sturz
nsturz/c0622-code-solutions pull request #18
Opened 2022-07-01 03:24 UTC by nsturz

<img width="1280" alt="Screen Shot 2022-06-30 at 8 18 28 PM" src="https://user-images.githubusercontent.com/94485412/176817372-36c040e5-010a-4d88-b186-432ddbbc0688.png">

2022-07-01 17:52 UTC, codingcodymiller requested changes
Last review didn't register in the LMS, submitting one mroe

2022-07-01 17:52 UTC, codingcodymiller commented on css-three-column-layout/index.html
> +      </div>
As I had discussed with the class when introducing this challenge, this is a reasonable thought on how to divide the layout into rows, but this makes it seem like the images are unrelated to the text in the row below it. You should group the icon, subheader, and subtext all together in one `column`. Also, If you intend to use a `row`, the child elements should generally always have a `column` class to set up their size. There are exceptions, but it's almost always the case that a `column` is required.

2022-07-01 20:21 UTC, nsturz commented on css-three-column-layout/index.html
> +      </div>
okay great, so just reiterating to make sure i understand - 

it looks like i need to create a row with 3 columns in it, and put a circle, subheader, and subtext in each column, right?

2022-07-01 22:02 UTC, codingcodymiller commented on css-three-column-layout/index.html
> +      </div>
Yup!

2022-07-01 22:03 UTC, codingcodymiller requested changes

2022-07-01 22:03 UTC, codingcodymiller commented on css-three-column-layout/styles.css
> +}
`column` classes should only have `flex-basis` applied to them. What size is this column supposed to be? You should give it an appropriate name and measurement.

2022-07-05 17:10 UTC, codingcodymiller requested changes

2022-07-05 17:10 UTC, codingcodymiller commented on css-three-column-layout/styles.css
>    padding-left: 2%;
This should be named `column-one-third`, and it should have a declaration of `flex-basis`, and **_nothing else_**

2022-07-06 16:23 UTC, codingcodymiller requested changes

2022-07-06 16:23 UTC, codingcodymiller commented on css-three-column-layout/styles.css
> +  flex-basis: auto%;
`auto%` is not a value. If this is a one third width column, this should be `33%`

2022-07-07 22:40 UTC, merged