completed css-two-column-layout exercise - Nick Sturz
nsturz/c0622-code-solutions pull request #20
Opened 2022-07-01 23:58 UTC by nsturz

<img width="1440" alt="Screen Shot 2022-07-01 at 4 56 08 PM" src="https://user-images.githubusercontent.com/94485412/176978634-70a75312-92ea-4e44-9b14-448f926012e4.png">

2022-07-05 17:17 UTC, codingcodymiller requested changes
Hey Nick, this is not making proper use of layout classes. Please review the `css-layout-classes` exercise in full before attempting to revise this again, you seem to have some fundamental misunderstandings of the concept.

2022-07-05 17:17 UTC, codingcodymiller commented on css-two-column-layout/index.html
> +    <div>
No `row`?

2022-07-09 20:08 UTC, nsturz commented
<img width="1280" alt="Screen Shot 2022-07-09 at 1 07 47 PM" src="https://user-images.githubusercontent.com/94485412/178121103-c1f7c53d-122d-4226-b394-4128f6e9d80f.png">

2022-07-11 17:26 UTC, codingcodymiller approved these changes

2022-07-13 04:14 UTC, merged