completed css-four-column-layout exercise - Nick Sturz
nsturz/c0622-code-solutions pull request #26
Opened 2022-07-06 06:09 UTC by nsturz

<img width="1280" alt="Screen Shot 2022-07-05 at 11 07 20 PM" src="https://user-images.githubusercontent.com/94485412/177480778-3164f457-80eb-49cd-a7ce-f0ddbce8a6ee.png">

2022-07-06 18:14 UTC, codingcodymiller requested changes

2022-07-06 18:14 UTC, codingcodymiller commented on css-four-column-layout/styles.css
> +}
This is not the proper way to make `column-` class rulesets. They should have a value that accurately represents the class name's stated size.

2022-07-06 18:14 UTC, codingcodymiller commented on css-four-column-layout/styles.css
> +}
I don't see these in use anywhere, you should delete styling that is not being used.

2022-07-09 21:13 UTC, nsturz commented on css-four-column-layout/styles.css
> +}
removed

2022-07-09 21:21 UTC, nsturz commented on css-four-column-layout/styles.css
> +}
was able to remove all CSS column rulesets altogether - styling can be achieved without them. Kept "column-one-fourth" classes  in HTML markup for reading purposes though.

2022-07-11 17:29 UTC, codingcodymiller approved these changes

2022-07-13 04:14 UTC, merged